apiVersion: v1
kind: Service
metadata:
  name: github-transfer-service
spec:
  selector:
    app: github-transfer-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 192.168.1.94
  type: LoadBalancer
