apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deployment
        image: muditsoni32/my-nginx-wordpress-image:latest
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: "192.168.1.20"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "test"
          - name: DB_PASSWORD
            value: "P@$$Admin"
          - name: DB_NAME
            value: "pipeline"