apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local  # Optional label
spec:
  storageClassName: local  # Adjust if needed
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"  # Use a more resilient solution if possible

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    app: my-application  # Optional label
spec:
  storageClassName: standard  # Match the PV's storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi