apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-config.php: |
    <?php
    define( 'DB_NAME', 'pipeline' );
    define( 'DB_USER', 'test' );
    define( 'DB_PASSWORD', 'P@$$Admin' );
    define( 'DB_HOST', '192.168.1.20' );
    ```